name: biop
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.5
  - torchvision=0.20
  - torchaudio=2.5
  - pytorch-cuda=12.1         
  - numpy=1.26
  - pandas=2.1
  - scipy=1.15
  - scikit-learn=1.6
  - matplotlib=3.9
  - seaborn=0.13
  - biopython=1.84
  - csvkit=2.0
  - powerlaw=1.4
  - jinja2
  - requests
  - pip
  - pip:
      - flash-attn==2.7.4.post1
      - transformers==4.52.4
      - tokenizers==0.21.1
      - huggingface-hub==0.33.0
      - safetensors==0.5.3
      - einops==0.8.1
      - tqdm==4.67.1
      - stripedhyena==0.2.2
      - regex==2024.11.6
      - fsspec==2025.5.1
      - hf-xet==1.1.3
      - evo-model==0.4
